src/notepad/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from notes.views import (
    note_list_view,
    finished_item,
    delete_item,
    recover_item)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view, name='note-list'),
    path('finished/<int:id>/', finished_item, name='finished_item'),
    path('deleted/<int:id>/', delete_item, name='delete_item'),
    path('recover/<int:id>/', recover_item, name='recover_item')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/notes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Notes(models.Model):
    LABEL_CHOICES = (
        ('P', 'primary'),
        ('SE', 'secondary'),
        ('W', 'warning'),
        ('S', 'success'),
        ('I', 'info'),
        ('D', 'dark'),
        ('L', 'light'),
        ('DA', 'danger'))

    title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_finished_item_url(self):
        return (reverse("finished_item", kwargs={'id': self.id}))

    def get_recover_item_url(self):
        return (reverse("recover_item", kwargs={'id': self.id}))

    def get_delete_item_url(self):
        return (reverse("delete_item", kwargs={'id': self.id}))

src/notes/forms.py
from .models import Notes
from django import forms


class NotesModelForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ('title', 'due_date', 'label')

src/notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Notes
from .forms import NotesModelForm

# Create your views here.


def note_list_view(request):
    form = NotesModelForm()
    if request.method == 'POST':
        print("$$$$")
        form = NotesModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('note-list')

    to_do_list = Notes.objects.filter(finished=False)
    print(len(to_do_list))
    completed_do_list = Notes.objects.filter(finished=True)
    context = {
        "to_do_list": to_do_list,
        "completed_list": completed_do_list,
        "form": form
    }
    return render(request, "note_list.html", context)


def finished_item(request, id):
    note = get_object_or_404(Notes, id=id)
    note.finished = True
    note.save()
    return redirect('note-list')


def delete_item(request, id):
    note = get_object_or_404(Notes, id=id)
    note.delete()
    return redirect('note-list')


def recover_item(request, id):
    note = get_object_or_404(Notes, id=id)
    note.finished = False
    note.save()
    return redirect('note-list')

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <script
      src="https://kit.fontawesome.com/49d2662d7b.js"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico" />

    <title>Starter Template for Bootstrap</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="https://example.com"
              id="dropdown01"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
              >Dropdown</a
            >
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
      </div>
    </nav>
    <div class="container">
      {% block content %} {% endblock content %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/templates/note_list.html
{% extends "base.html" %}
{% block content %}

  <div class="text-center mt-5">
    <h1>To-Do List   
    <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      <i class="fas fa-plus fa-sm"></i>
    </a>
  </h1>
    </div>
    <div class="collapse" id="collapseExample">
    <div class="card card-body">
    <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_title">Title</label>
              {{form.title}}
          </div>
          <div class="form-group">
            <label for="id_due_date">Due Date</label>
              {{form.due_date}}
          </div>
          <div class="form-group">
            <label for="id_label">Label</label>
              {{form.label}}
          </div>
          <button type="submit" class = "btn btn-primary">CREATE</button>
        </form>
    </div>
    </div> 
  <hr/>
      <div class="row">
        {% for element in to_do_list %}
        <div class="col-12">
          {% include "note_snippet.html" with element=element type="COMPLETED"%}
      </div>
      </div>
    </div>
        {% endfor %}         
  </div>
  <div class="text-center mt-5">
    <h1>Finished Tasks<h1>
  </div>
  <hr/>
  <div class="row">
    {% for element in completed_list %}
      <div class="col-12">
         {% include "note_snippet.html" with element=element type="RECOVER" %}
      </div>
    </div>
    {% endfor %}         
  </div>
  {% endblock content %}

src/templates/note_snippet.html
<style>
  h2 {
      position: relative;
    }
  
  .icons{
      position: absolute;
      right: 5px;
    }
  
  </style>
 
 <div class="card">
    <div class="card-body">          
      <h2>{{element.title}} <span class="badge badge-{{element.get_label_display}}">{{ element.due_date}}</span>
        <span class="icons">
          {% if type == "RECOVER" %}
          <a href="{{ element.get_recover_item_url }}"><i class="fas fa-times"></i></a>
          {% else %}
          <a href="{{ element.get_finished_item_url }}"><i class="fas fa-check"></i></a>
          {% endif %}
          <a href="{{ element.get_delete_item_url }}"><i class="fas fa-trash-alt" style="color:red"></i></a>
        </span></h2>
    </div>
</div>